context.exec = [
    {
        path = "pactl"
        args = "load-module module-null-sink sink_name=Sink_Spotify sink_properties=device.description=Sink_Spotify"
    },
    {
        path = "pactl"
        args = "load-module module-null-sink sink_name=Sink_Discord sink_properties=device.description=Sink_Discord"
    },
    {
        path = "pactl"
        args = "load-module module-null-sink sink_name=Sink_PC_Audio sink_properties=device.description=Sink_PC_Audio"
    },
    {
        path = "pactl"
        args = "load-module module-null-sink sink_name=Sink_PC_Game sink_properties=device.description=Sink_PC_Game"
    },
    {
        path = "pactl"
        args = "load-module module-null-sink sink_name=Sink_PC_Speakers sink_properties=device.description=Sink_PC_Speakers"
    },
]