# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    kb_layout = br,us
    kb_variant = abnt2,
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}
